#include "MOTION_DEFINE.h"
#include "FAS_EziMOTIONPlusR.h"

//COMMON
#define MAX_CHAR									512

//#define	MOTION_STR_PARA_FILENAME					 _T("Motion.par")
//#define IO_STR_PARA_FILENAME						_T("DIOLabel.ini")
//#define MOTINO_STR_PARA_FILEPATH					 _T("D:\\DATABASE\\SYSTEM\\")

#define DEFAULT_PORT_NUMBER							10
#define DEFAULT_BAUDRATE							115200

#define SERVO_OFF									0
#define SERVO_ON									1

//MOTION
#define MOT_PROCESS_MAX_NUM							1
#define MOT_STATUS_MAX_NUM							1
#define MAX_AXIS_NUM								1

//AXIS DEFINE
#define AXIS_Z										0

#define AXIS_MOVE_TYPE_JOG							0
#define AXIS_MOVE_TYPE_STEP							1
#define AXIS_BASE_VEL								10000

//TIME OUT
//#define TIMEOUT_SAFE_SENSOR							10

//ALARM MESSAGE
//#define ALARM_MSG_EMO								"Detected EMO !(1:100)"
//#define ALARM_MSG_AREA_SENSOR						"Decteded AREA SENSOR!(1:110)"

//ALARM CODE	
//#define ALARM_CODE_EMO								"Err0001"
//#define ALARM_CODE_AREA_SENSOR						"Err0002"

//#define OP_EMS_CHECK								0
//#define OP_AREA_SENSOR_CHECK						1

//LAMP DEFINE
//#define COLOR_LAMP_RED								0
//#define COLOR_LAMP_YELLOW							1
//#define COLOR_LAMP_GREEN							2
//#define COLOR_LAMP_OFF								3

//IO

#define MAX_OUTPUT_CNT								9
#define MAX_INPUT_CNT								9
/*
	#define OUTPUT_000_TOWER_LAMP_RED					SERVO_OUT_BITMASK_USEROUT0		// SLAVE : AXIS_0
	#define OUTPUT_001_TOWER_LAMP_YELLOW				SERVO_OUT_BITMASK_USEROUT1
	#define OUTPUT_002_TOWER_LAMP_GREEN					SERVO_OUT_BITMASK_USEROUT2
	#define OUTPUT_003_TOWER_LAMP_BUZZER				SERVO_OUT_BITMASK_USEROUT3
	#define OUTPUT_004_SOL_Z_SYLINDER_LEFT_UP			SERVO_OUT_BITMASK_USEROUT0		// SLAVE : AXIS_1
	#define OUTPUT_005_SOL_Z_SYLINDER_LEFT_DN			SERVO_OUT_BITMASK_USEROUT1
	#define OUTPUT_006_SOL_Z_SYLINDER_RIGHT_UP			SERVO_OUT_BITMASK_USEROUT2
	#define OUTPUT_007_SOL_Z_SYLINDER_RIGHT_DN			SERVO_OUT_BITMASK_USEROUT3
	#define OUTPUT_008_SOL_X_SYLINDER_LEFT_FW			SERVO_OUT_BITMASK_USEROUT4
	#define OUTPUT_009_SOL_X_SYLINDER_LEFT_BK			SERVO_OUT_BITMASK_USEROUT5
	#define OUTPUT_010_SOL_X_SYLINDER_RIGHT_FW			SERVO_OUT_BITMASK_USEROUT6
	#define OUTPUT_011_SOL_X_SYLINDER_RIGHT_BK			SERVO_OUT_BITMASK_USEROUT7


#define MAX_INPUT_CNT								9
	#define INPUT_000_EMO_BUTTON						SERVO_IN_BITMASK_USERIN0		// SLAVE : AXIS_0
	#define INPUT_001_LEFT_START_BUTTON					SERVO_IN_BITMASK_USERIN1
	#define INPUT_002_RIGHT_START_BUTTON				SERVO_IN_BITMASK_USERIN2
	#define INPUT_003_AREA_SENSOR						SERVO_IN_BITMASK_USERIN3
	#define INPUT_004_Z_SYLINDER_LEFT_UP				SERVO_IN_BITMASK_USERIN0		// SLAVE : AXIS_1
	#define INPUT_005_Z_SYLINDER_LEFT_DN				SERVO_IN_BITMASK_USERIN1
	#define INPUT_006_Z_SYLINDER_RIGHT_UP				SERVO_IN_BITMASK_USERIN2
	#define INPUT_007_Z_SYLINDER_RIGHT_DN				SERVO_IN_BITMASK_USERIN3
	#define INPUT_008_X_SYLINDER_LEFT_FW				SERVO_IN_BITMASK_USERIN4
	#define INPUT_009_X_SYLINDER_LEFT_BK				SERVO_IN_BITMASK_USERIN5
	#define INPUT_010_X_SYLINDER_RIGHT_FW				SERVO_IN_BITMASK_USERIN6
	#define INPUT_011_X_SYLINDER_RIGHT_BK				SERVO_IN_BITMASK_USERIN7
*/

//COLOR
const COLORREF BACKGROUND_COLOR = RGB(230, 230, 230);
const COLORREF CLOUDBLUE = RGB(128, 184, 223);
const COLORREF WHITE = RGB(255, 255, 255);
const COLORREF BLACK = RGB(1, 1, 1);
const COLORREF DKGRAY = RGB(128, 128, 128);
const COLORREF LTGRAY = RGB(192, 192, 192);
const COLORREF LTYELLOW = RGB(255, 255, 128);
const COLORREF YELLOW = RGB(255, 255, 0);
const COLORREF DKYELLOW = RGB(128, 128, 0);
const COLORREF RED = RGB(255, 0, 0);
const COLORREF DKRED = RGB(128, 0, 0);
const COLORREF BLUE = RGB(0, 0, 255);
const COLORREF DKBLUE = RGB(0, 0, 220);
const COLORREF CYAN = RGB(0, 255, 255);
const COLORREF DKCYAN = RGB(0, 128, 128);
const COLORREF GREEN = RGB(0, 255, 0);
const COLORREF DKGREEN = RGB(0, 128, 0);
const COLORREF MAGENTA = RGB(255, 0, 255);
const COLORREF DKMAGENTA = RGB(128, 0, 128);
const COLORREF BASIC = RGB(212, 208, 200);
const COLORREF LTSKYBLUE = RGB(128, 255, 255);
const COLORREF LTVIOLET = RGB(157, 157, 255);
const COLORREF DATA_ITEM_CHANGE_BACKGROUND_COLOR = CYAN;
const COLORREF DATA_ITEM_CHANGE_TEXT_COLOR = BLACK;
const COLORREF DATA_ITEM_TEXT_COLOR = BLACK;
const COLORREF DATA_ITEM_BACKGROUND_COLOR = CYAN;
